# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LatexDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LatexDemo
  pod 'iosMath'

  target 'LatexDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LatexDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LatexDemo-tvOS

  target 'LatexDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
